version: '2'
services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./storage/database:/var/lib/mysql
      - ./magento.sql:/docker-entrypoint-initdb.d/magento.sql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=magento
  apache:
    build: .
    volumes:
      - ./magento:/var/www
    ports:
      - "8080:80"
    depends_on:
      - db
